AWSTemplateFormatVersion: 2010-09-09
Description: Mozilla Multi Account Manager for AWS GuardDuty
Metadata:
  Source: https://github.com/mozilla/guardduty-multi-account-manager/tree/master/cloudformation
Parameters:
  AccountFilterList:
    Type: String
    Default: ''
    # Default: 656532927350
    Description: Space delimited list of account IDs to filter on. Leave this empty to process all accounts
  OrganizationAccountArns:
    Type: String
    Default: ''
    Description: >
      ARNs of IAM Roles to assume in order to query the AWS Organization parents
      if the Org parents are different AWS accounts. Leave this empty if you are
      deploying within a single AWS Organization parent account
Mappings:
  Variables:
    CloudFormationTemplate:
      Prefix: https://s3-us-west-2.amazonaws.com/public.us-west-2.infosec.mozilla.org/guardduty-multi-account-manager/cf/
    LambdaCode:
      BucketNamePrefix: public.
      BucketNameSuffix: .infosec.mozilla.org
      DirectoryPath: guardduty-multi-account-manager/lambda/
Resources:
  GuardDutyInvitationManager:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
        - Key: application
          Value: guardduty-multi-account-manager
      TemplateURL: !Join [ '', [ !FindInMap [ Variables, CloudFormationTemplate, Prefix ], guardduty-invitation-manager.yml ] ]
      Parameters:
        LambdaCodeS3BucketNamePrefix: !FindInMap [ Variables, LambdaCode, BucketNamePrefix ]
        LambdaCodeS3BucketNameSuffix: !FindInMap [ Variables, LambdaCode, BucketNameSuffix ]
        LambdaCodeS3Path: !FindInMap [ Variables, LambdaCode, DirectoryPath ]
        AccountFilterList: !Ref AccountFilterList
        OrganizationAccountArns: !Ref OrganizationAccountArns
  GuardDutyEventNormalization:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
        - Key: application
          Value: guardduty-multi-account-manager
      TemplateURL: !Join [ '', [ !FindInMap [ Variables, CloudFormationTemplate, Prefix ], guardduty-event-normalization.yml ] ]
      Parameters:
        LambdaCodeS3BucketNamePrefix: !FindInMap [ Variables, LambdaCode, BucketNamePrefix ]
        LambdaCodeS3BucketNameSuffix: !FindInMap [ Variables, LambdaCode, BucketNameSuffix ]
        LambdaCodeS3Path: !FindInMap [ Variables, LambdaCode, DirectoryPath ]
